config/routes.rb
Blockalyser::Application.routes.draw do
  resources :mosaics

  match 'image' => 'image#index'
  match 'image/show' => 'image#show'
  match 'image/create' => 'image#create'
  match 'mosaic/new' =>'mosaics#new'

end

app/models/image.rb
class Image < ActiveRecord::Base

#    has_attached_file :photo,
#    :styles => {
#      :thumbnail => "185x185#",
#    },
#    :storage => :s3,
#    :s3_credentials => "#{Rails.root.to_s}/config/s3.yml",
#    :s3_host_name => "s3-eu-west-1.amazonaws.com",
#    :s3_protocol => "https",
#    :path => ":class/:id/:style_:basename.:extension",
#    :bucket => "photo.blockalyser.com",
#    :url  => ":s3_eu_url"

    def uploaded_file=(incoming_file)
        self.filename = incoming_file.original_filename
        self.content_type = incoming_file.content_type
        self.data = incoming_file.read
    end

    def filename=(new_filename)
        write_attribute("filename", sanitize_filename(new_filename))
    end

    private
    def sanitize_filename(filename)
        #get only the filename, not the whole path (from IE)
        just_filename = File.basename(filename)
        #replace all non-alphanumeric, underscore or periods with underscores
        just_filename.gsub(/[^\w\.\-]/, '_')
    end
end

app/models/mosaic.rb
class Mosaic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/image_controller.rb
class ImageController < ApplicationController

  def upload
    @image = Image.new()
    #save_result = DataFile.save(params[:upload])

    #@file = save_result[0]

    #@image.thumb_height = save_result[1]
    #@image.thumb_width = save_result[2]

    #@image.filename = @file

    @image.photo = params[:photo]

    @image.user = -1

    if @image.save
      render :action => :show
    else
      render :action => "index"
    end
  end

  def index
  end

  def show
      @image = Image.find(params[:id])
      send_data @image.data, :filename => @image.file_name, :type => @image.content_type
      puts @image
  end

  def create
      return if params[:attachment].blank?

      @image = Image.new
      @image.uploaded_file = params[:attachment]

      if @image.save
          puts "All good. Saved on create and rendering to :Show"
          flash[:notice] = "Thank you for your submission..."
          render :action => :show
      else
          puts "Nope. Cocked up, this isn't happening, failing to :index'"
          flash[:error] = "There was a problem submitting your attachment."
          render :action => :index
      end
  end

end

app/controllers/mosaics_controller.rb
class MosaicsController < ApplicationController
  # GET /mosaics
  # GET /mosaics.xml
  def index
    @mosaics = Mosaic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mosaics }
    end
  end

  # GET /mosaics/1
  # GET /mosaics/1.xml
  def show
    @mosaic = Mosaic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mosaic }
    end
  end

  # GET /mosaics/new
  # GET /mosaics/new.xml
  def new
    puts params[:image_data]

    @mosaic = Mosaic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mosaic }
    end
  end

  # GET /mosaics/1/edit
  def edit
    @mosaic = Mosaic.find(params[:id])
  end

  # POST /mosaics
  # POST /mosaics.xml
  def create
    @mosaic = Mosaic.new(params[:mosaic])

    respond_to do |format|
      if @mosaic.save
        format.html { redirect_to(@mosaic, :notice => 'Mosaic was successfully created.') }
        format.xml  { render :xml => @mosaic, :status => :created, :location => @mosaic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mosaic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mosaics/1
  # PUT /mosaics/1.xml
  def update
    @mosaic = Mosaic.find(params[:id])

    respond_to do |format|
      if @mosaic.update_attributes(params[:mosaic])
        format.html { redirect_to(@mosaic, :notice => 'Mosaic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mosaic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mosaics/1
  # DELETE /mosaics/1.xml
  def destroy
    @mosaic = Mosaic.find(params[:id])
    @mosaic.destroy

    respond_to do |format|
      format.html { redirect_to(mosaics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/mosaics_helper.rb
module MosaicsHelper
end

app/views/image/index.html.erb
<img src="/images/splash.png" />
<h1>Create your mosaic:</h1>
<aside>
<form action="/image/create" enctype="multipart/form-data" method="post" name="UploadForm">
    <div>
        <h2>Upload your image:</h2>
        <input type="file" name="attachment" id="attachment" size="40"><a href="javascript:document.UploadForm.submit()" class="button save">Upload</a>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor vestibulum massa id tristique. Integer et ligula sed magna porttitor vehicula vel consectetur erat. Nunc massa neque, blandit ut feugiat ac, suscipit et lectus. Cras neque libero, vulputate quis tincidunt pellentesque, rhoncus et ligula. Nulla vitae dapibus justo. Mauris nec purus vitae nisi dictum suscipit sit amet ut metus. Integer facilisis rhoncus dictum. Donec tempor libero ut urna egestas sed hendrerit enim dapibus. Nulla vulputate nulla quis leo adipiscing dapibus. Aliquam id metus vel dui adipiscing iaculis nec vel leo. Donec mollis, mauris in posuere sodales, est metus tincidunt orci, eu tempor magna diam quis lacus. Suspendisse elit erat, bibendum a laoreet at, rhoncus ut ipsum. Aliquam aliquet lacus et nulla mollis suscipit. Nulla lacinia nibh ac metus bibendum ullamcorper. In convallis, risus vel rhoncus laoreet, urna erat ultricies lacus, at vestibulum dolor lectus vel odio.</p>
</form>
<div>
    Order:
    Instructions £3 (paypal)
    Completed, Framed Mosaic £5000 (paypal)
    (We're not joking, this is a huge undertaking to make even one...)
<div>
</aside>
<p><a href="examples">See some completed examples...</a></p>

app/views/image/show.html.erb
<canvas id="srcImg"></canvas>
<canvas id="clrImg" class="off"></canvas>
<div>
    <form action="/mosaic/new" method="post" name="submit_image">
        <input type="hidden" id="imageFile" value="/image/show?id=<%= @image.id %>"/>
        <p>Height: <input type="text" name="destHeight" id="destHeight" onblur="checkAspect(this)"/></p>
        <p>Width: <input type="text" name="destWidth" id="destWidth" onblur="checkAspect(this)"/></p>
        <p>Lock Aspect Ratio: <input type="checkbox" id="preserveAspect" checked/></p>

        <p>Colour: <select id="colourStyleSelection"><option value="11">Glorious 11 Colour</option><option value="3">Stylish 3 colour Grey Scale</option><option value="2">Avant Garde 2 Colour B&W</option></select></p>
        <p>Enhance White Balance: <input id="whiteBalance" type="range" min="0" max="100" value="15" /></p>
        <p><a href="javascript: render()" class="button next">Render</a><a href="javascript: calculate()" class="button next">Calculate</a></p>


        <p><a href="javascript: document.submit_image.submit()" class="button save">Generate Mosaic</a></p>

        <input type="hidden" id="image_data" name="image_data"/>
    </form>
    Order:
    Instructions £3 (paypal)
    Completed, Framed Mosaic £5000 (paypal)
    (We're not joking, this is a huge undertaking to make even one...)
</div>
<p/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Blockalyser - making beautiful images into beautiful blocs</title>
	<script src="/javascripts/core.js" type="text/javascript"></script>
	<link rel="stylesheet" href="/stylesheets/css.css" type="text/css"/>
  	<link rel="stylesheet" href="/stylesheets/button.css" type="text/css"/>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
</head>
<body onload="startup()">
	<header>
		<h1>blockalyser</h1>
		<h2>making beautiful images into beautiful blocks</h2>
	</header>
	<section>
      <article>
        <%= yield %>
      </article>
	</section>
	<footer>
		<div>
			<h1>About</h1>
			<article>Blockayser by <a href="http://www.wawra.co.uk">Michael Wawra</a>, copyright 2011. Blockalyser is in no way related to any manufacturers of toy building bricks, nor is it in any way supported by them. All rights acknowledged.</article>
		</div>
		<div>
			<h1>Sitemap</h1>
			<article>
			<ul>
				<li>Home</li>
				<li>About</li>
				<li>Create new Mosaic</li>
				<li>Find Mosaic</li>
				<li>Help</li>
			</ul>
			</article>
		</div>
		<div>
			<h1>Conditions and Warranties</h1>
			<article>Converting images to mosaics is a very imprecise science. Therefore this application is to be treated as a 'toy' and must not be relied upon for it's accuracy. Payments are made for the necessary processing or manufacture, not for the instructions which may contain errors (especially at right and bottom edges).</article>
		</div>
		<div>
			<article>
				<br/>
				<a href="http://twitter.com/xmjw" title="Twitter"><img src="/images/smicons/32/twitter.png"/></a>
				<a href="http://www.linkedin.com/in/michaelwawra" title="LinkedIn"><img src="/images/smicons/32/linkedin.png"/></a>
				<a href="http://facebook.com/m.wawra" title="Facebook"><img src="/images/smicons/32/facebook.png"/></a>
				<a href="http://wawra.co.uk" title="Wawwra.co.uk"><img src="/images/w.png"/></a>
				<br/>
				<br>
				<a href="https://www.minutebox.com/profiles/michael"><img src="https://www.minutebox.com/images/button-buy-now.png"></a>
			</article>
		</div>
	</footer>
</body>
</html>

app/views/mosaics/_form.html.erb
<%= form_for(@mosaic) do |f| %>
  <% if @mosaic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mosaic.errors.count, "error") %> prohibited this mosaic from being saved:</h2>

      <ul>
      <% @mosaic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :height %><br />
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br />
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mosaics/edit.html.erb
<h1>Editing mosaic</h1>

<%= render 'form' %>

<%= link_to 'Show', @mosaic %> |
<%= link_to 'Back', mosaics_path %>

app/views/mosaics/index.html.erb
<h1>Listing mosaics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Height</th>
    <th>Width</th>
    <th>State</th>
    <th>Source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mosaics.each do |mosaic| %>
  <tr>
    <td><%= mosaic.name %></td>
    <td><%= mosaic.user %></td>
    <td><%= mosaic.height %></td>
    <td><%= mosaic.width %></td>
    <td><%= mosaic.state %></td>
    <td><%= mosaic.source %></td>
    <td><%= link_to 'Show', mosaic %></td>
    <td><%= link_to 'Edit', edit_mosaic_path(mosaic) %></td>
    <td><%= link_to 'Destroy', mosaic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mosaic', new_mosaic_path %>

app/views/mosaics/new.html.erb
<p>brick <a href="#" class="button next">Next</a> <a href="#" class="button previous">Previous</a> <a href="#" class="button next">Reset</a> <a href="#" class="button next">Save</a></p>
<canvas id="srcImg" class="instructor"></canvas>
<p>Buy a shoppin list, of buy your finished, framed, mosaic, direct to your door in our <a href=="/shop">shop</a></p>

app/views/mosaics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mosaic.name %>
</p>

<p>
  <b>User:</b>
  <%= @mosaic.user %>
</p>

<p>
  <b>Height:</b>
  <%= @mosaic.height %>
</p>

<p>
  <b>Width:</b>
  <%= @mosaic.width %>
</p>

<p>
  <b>State:</b>
  <%= @mosaic.state %>
</p>

<p>
  <b>Source:</b>
  <%= @mosaic.source %>
</p>


<%= link_to 'Edit', edit_mosaic_path(@mosaic) %> |
<%= link_to 'Back', mosaics_path %>